// eslint-disable-next-line @typescript-eslint/no-unused-vars -- used for links in jsdoc
import type { GardeningAction } from "./value-objects";

/**
 * Frozen map of action kinds. Values are stable strings for APIs, persistence, and logs.
 * Adding a kind here requires a matching variant on {@link GardeningAction}
 * and a branch in any UI that lists actions.
 */
export const GardeningActionType = Object.freeze({
	/** Applying water (hose, can, irrigation, rain catch, etc.). */
	watering: "watering",
	/** Feed or soil amendment. */
	fertilization: "fertilization",
	/** Cutting or shaping plant material. */
	pruning: "pruning",
	/** Taking fruit, veg, flowers, or other yield. */
	harvesting: "harvesting",
	/** Moving a plant or changing its placement (pot, bed, etc.). */
	transplanting: "transplanting",
	/** Freeform note attached to a plant or location. */
	note: "note",
} as const);

/** Union of all keys in {@link GardeningActionType}; use for typing `type` on actions. */
export type GardeningActionType = (typeof GardeningActionType)[keyof typeof GardeningActionType];

export const ItemPresentationIconKey = Object.freeze({
	action_watering: "action.watering",
	action_fertilization: "action.fertilization",
	action_pruning: "action.pruning",
	action_harvesting: "action.harvesting",
	action_transplanting: "action.transplanting",
	action_note: "action.note",

	// generic
	generic_carrot: "carrot",
	generic_leaf: "leaf",
	generic_apple: "apple",
	generic_cherry: "cherry",
	generic_leaf2: "leaf2",
	generic_basket: "basket",
	generic_flower: "flower",
	generic_grain: "grain",
	generic_carrot_off: "carrot-off",
	generic_flower_filled: "flower-filled",
	generic_leaf_filled: "leaf-filled",

	// categories
	category_vegetables: "category.vegetables",
	category_herbs: "category.herbs",
	category_fruits: "category.fruits",
	category_berries: "category.berries",
	category_leafyGreens: "category.leafyGreens",
	category_alliums: "category.alliums",
	category_brassicas: "category.brassicas",
	category_legumes: "category.legumes",
	category_rootCrops: "category.rootCrops",
	category_flowers: "category.flowers",
	category_microgreens: "category.microgreens",
	category_coverCrops: "category.coverCrops",

	// vegetables
	species_vegetables_tomato: "vegetables.tomato",
	species_vegetables_cucumber: "vegetables.cucumber",
	species_vegetables_zucchini: "vegetables.zucchini",
	species_vegetables_eggplant: "vegetables.eggplant",
	species_vegetables_bellPepper: "vegetables.bellPepper",
	species_vegetables_chiliPepper: "vegetables.chiliPepper",
	species_vegetables_pumpkin: "vegetables.pumpkin",
	species_vegetables_squash: "vegetables.squash",
	species_vegetables_corn: "vegetables.corn",
	species_vegetables_okra: "vegetables.okra",
	species_vegetables_artichoke: "vegetables.artichoke",
	species_vegetables_celery: "vegetables.celery",
	species_vegetables_asparagus: "vegetables.asparagus",
	species_vegetables_rhubarb: "vegetables.rhubarb",
	species_vegetables_sweetPotato: "vegetables.sweetPotato",
	species_vegetables_tomatillo: "vegetables.tomatillo",
	species_vegetables_pattypanSquash: "vegetables.pattypanSquash",
	species_vegetables_chayote: "vegetables.chayote",
	species_vegetables_kohlrabi: "vegetables.kohlrabi",
	species_vegetables_fennel: "vegetables.fennel",

	// herbs
	species_herbs_basil: "herbs.basil",
	species_herbs_parsley: "herbs.parsley",
	species_herbs_cilantro: "herbs.cilantro",
	species_herbs_dill: "herbs.dill",
	species_herbs_mint: "herbs.mint",
	species_herbs_oregano: "herbs.oregano",
	species_herbs_thyme: "herbs.thyme",
	species_herbs_rosemary: "herbs.rosemary",
	species_herbs_sage: "herbs.sage",
	species_herbs_chives: "herbs.chives",
	species_herbs_tarragon: "herbs.tarragon",
	species_herbs_marjoram: "herbs.marjoram",
	species_herbs_lavender: "herbs.lavender",
	species_herbs_lemonBalm: "herbs.lemonBalm",
	species_herbs_bayLaurel: "herbs.bayLaurel",
	species_herbs_lemongrass: "herbs.lemongrass",
	species_herbs_stevia: "herbs.stevia",
	species_herbs_chervil: "herbs.chervil",
	species_herbs_summerSavory: "herbs.summerSavory",
	species_herbs_winterSavory: "herbs.winterSavory",

	// fruits
	species_fruits_apple: "fruits.apple",
	species_fruits_pear: "fruits.pear",
	species_fruits_peach: "fruits.peach",
	species_fruits_plum: "fruits.plum",
	species_fruits_apricot: "fruits.apricot",
	species_fruits_cherry: "fruits.cherry",
	species_fruits_fig: "fruits.fig",
	species_fruits_persimmon: "fruits.persimmon",
	species_fruits_quince: "fruits.quince",
	species_fruits_grape: "fruits.grape",
	species_fruits_kiwi: "fruits.kiwi",
	species_fruits_melon: "fruits.melon",
	species_fruits_watermelon: "fruits.watermelon",
	species_fruits_pineapple: "fruits.pineapple",
	species_fruits_pomegranate: "fruits.pomegranate",
	species_fruits_orange: "fruits.orange",
	species_fruits_lemon: "fruits.lemon",
	species_fruits_lime: "fruits.lime",
	species_fruits_mango: "fruits.mango",
	species_fruits_papaya: "fruits.papaya",

	// berries
	species_berries_strawberry: "berries.strawberry",
	species_berries_blueberry: "berries.blueberry",
	species_berries_raspberry: "berries.raspberry",
	species_berries_blackberry: "berries.blackberry",
	species_berries_gooseberry: "berries.gooseberry",
	species_berries_redCurrant: "berries.redCurrant",
	species_berries_blackCurrant: "berries.blackCurrant",
	species_berries_whiteCurrant: "berries.whiteCurrant",
	species_berries_cranberry: "berries.cranberry",
	species_berries_lingonberry: "berries.lingonberry",
	species_berries_elderberry: "berries.elderberry",
	species_berries_mulberry: "berries.mulberry",
	species_berries_boysenberry: "berries.boysenberry",
	species_berries_loganberry: "berries.loganberry",
	species_berries_huckleberry: "berries.huckleberry",
	species_berries_serviceberry: "berries.serviceberry",
	species_berries_seaBuckthorn: "berries.seaBuckthorn",
	species_berries_aronia: "berries.aronia",
	species_berries_cloudberry: "berries.cloudberry",
	species_berries_jostaberry: "berries.jostaberry",

	// leafy-greens
	species_leafyGreens_lettuce: "leafyGreens.lettuce",
	species_leafyGreens_spinach: "leafyGreens.spinach",
	species_leafyGreens_kale: "leafyGreens.kale",
	species_leafyGreens_arugula: "leafyGreens.arugula",
	species_leafyGreens_swissChard: "leafyGreens.swissChard",
	species_leafyGreens_collardGreens: "leafyGreens.collardGreens",
	species_leafyGreens_endive: "leafyGreens.endive",
	species_leafyGreens_escarole: "leafyGreens.escarole",
	species_leafyGreens_mustardGreens: "leafyGreens.mustardGreens",
	species_leafyGreens_bokChoy: "leafyGreens.bokChoy",
	species_leafyGreens_romaine: "leafyGreens.romaine",
	species_leafyGreens_radicchio: "leafyGreens.radicchio",
	species_leafyGreens_watercress: "leafyGreens.watercress",
	species_leafyGreens_mizuna: "leafyGreens.mizuna",
	species_leafyGreens_tatsoi: "leafyGreens.tatsoi",
	species_leafyGreens_newZealandSpinach: "leafyGreens.newZealandSpinach",
	species_leafyGreens_purslane: "leafyGreens.purslane",
	species_leafyGreens_sorrel: "leafyGreens.sorrel",
	species_leafyGreens_malabarSpinach: "leafyGreens.malabarSpinach",
	species_leafyGreens_chicory: "leafyGreens.chicory",

	// alliums
	species_alliums_onion: "alliums.onion",
	species_alliums_garlic: "alliums.garlic",
	species_alliums_leek: "alliums.leek",
	species_alliums_shallot: "alliums.shallot",
	species_alliums_scallion: "alliums.scallion",
	species_alliums_garlicChive: "alliums.garlicChive",
	species_alliums_onionChive: "alliums.onionChive",
	species_alliums_welshOnion: "alliums.welshOnion",
	species_alliums_walkingOnion: "alliums.walkingOnion",
	species_alliums_rakkyo: "alliums.rakkyo",
	species_alliums_elephantGarlic: "alliums.elephantGarlic",
	species_alliums_ramps: "alliums.ramps",
	species_alliums_garlicChives: "alliums.garlicChives",
	species_alliums_springOnion: "alliums.springOnion",
	species_alliums_redOnion: "alliums.redOnion",
	species_alliums_yellowOnion: "alliums.yellowOnion",
	species_alliums_whiteOnion: "alliums.whiteOnion",
	species_alliums_pearlOnion: "alliums.pearlOnion",
	species_alliums_cipolliniOnion: "alliums.cipolliniOnion",
	species_alliums_societyGarlic: "alliums.societyGarlic",

	// brassicas
	species_brassicas_cabbage: "brassicas.cabbage",
	species_brassicas_broccoli: "brassicas.broccoli",
	species_brassicas_cauliflower: "brassicas.cauliflower",
	species_brassicas_brusselsSprouts: "brassicas.brusselsSprouts",
	species_brassicas_broccolini: "brassicas.broccolini",
	species_brassicas_napaCabbage: "brassicas.napaCabbage",
	species_brassicas_savoyCabbage: "brassicas.savoyCabbage",
	species_brassicas_redCabbage: "brassicas.redCabbage",
	species_brassicas_romanesco: "brassicas.romanesco",
	species_brassicas_turnip: "brassicas.turnip",
	species_brassicas_rutabaga: "brassicas.rutabaga",
	species_brassicas_daikon: "brassicas.daikon",
	species_brassicas_wasabi: "brassicas.wasabi",
	species_brassicas_horseradish: "brassicas.horseradish",
	species_brassicas_komatsuna: "brassicas.komatsuna",
	species_brassicas_broccoliRaab: "brassicas.broccoliRaab",
	species_brassicas_mustardCabbage: "brassicas.mustardCabbage",
	species_brassicas_chineseBroccoli: "brassicas.chineseBroccoli",
	species_brassicas_pakChoi: "brassicas.pakChoi",
	species_brassicas_canola: "brassicas.canola",

	// legumes
	species_legumes_pea: "legumes.pea",
	species_legumes_snapPea: "legumes.snapPea",
	species_legumes_snowPea: "legumes.snowPea",
	species_legumes_greenBean: "legumes.greenBean",
	species_legumes_runnerBean: "legumes.runnerBean",
	species_legumes_limaBean: "legumes.limaBean",
	species_legumes_favaBean: "legumes.favaBean",
	species_legumes_chickpea: "legumes.chickpea",
	species_legumes_lentil: "legumes.lentil",
	species_legumes_soybean: "legumes.soybean",
	species_legumes_peanut: "legumes.peanut",
	species_legumes_cowpea: "legumes.cowpea",
	species_legumes_pigeonPea: "legumes.pigeonPea",
	species_legumes_blackEyedPea: "legumes.blackEyedPea",
	species_legumes_adzukiBean: "legumes.adzukiBean",
	species_legumes_mungBean: "legumes.mungBean",
	species_legumes_kidneyBean: "legumes.kidneyBean",
	species_legumes_navyBean: "legumes.navyBean",
	species_legumes_pintoBean: "legumes.pintoBean",
	species_legumes_borlottiBean: "legumes.borlottiBean",

	// root-crops
	species_rootCrops_carrot: "rootCrops.carrot",
	species_rootCrops_beet: "rootCrops.beet",
	species_rootCrops_radish: "rootCrops.radish",
	species_rootCrops_parsnip: "rootCrops.parsnip",
	species_rootCrops_turnipRoot: "rootCrops.turnipRoot",
	species_rootCrops_celeriac: "rootCrops.celeriac",
	species_rootCrops_salsify: "rootCrops.salsify",
	species_rootCrops_scorzonera: "rootCrops.scorzonera",
	species_rootCrops_yacon: "rootCrops.yacon",
	species_rootCrops_jicama: "rootCrops.jicama",
	species_rootCrops_burdock: "rootCrops.burdock",
	species_rootCrops_skirret: "rootCrops.skirret",
	species_rootCrops_cassava: "rootCrops.cassava",
	species_rootCrops_taro: "rootCrops.taro",
	species_rootCrops_yam: "rootCrops.yam",
	species_rootCrops_ginger: "rootCrops.ginger",
	species_rootCrops_turmeric: "rootCrops.turmeric",
	species_rootCrops_horseradishRoot: "rootCrops.horseradishRoot",
	species_rootCrops_daikonRoot: "rootCrops.daikonRoot",
	species_rootCrops_rutabagaRoot: "rootCrops.rutabagaRoot",

	// flowers
	species_flowers_marigold: "flowers.marigold",
	species_flowers_nasturtium: "flowers.nasturtium",
	species_flowers_calendula: "flowers.calendula",
	species_flowers_borage: "flowers.borage",
	species_flowers_chamomile: "flowers.chamomile",
	species_flowers_sunflower: "flowers.sunflower",
	species_flowers_zinnia: "flowers.zinnia",
	species_flowers_cosmos: "flowers.cosmos",
	species_flowers_lavenderFlower: "flowers.lavenderFlower",
	species_flowers_echinacea: "flowers.echinacea",
	species_flowers_yarrow: "flowers.yarrow",
	species_flowers_alyssum: "flowers.alyssum",
	species_flowers_phacelia: "flowers.phacelia",
	species_flowers_cornflower: "flowers.cornflower",
	species_flowers_dahlia: "flowers.dahlia",
	species_flowers_pansy: "flowers.pansy",
	species_flowers_viola: "flowers.viola",
	species_flowers_snapdragon: "flowers.snapdragon",
	species_flowers_sweetPeaFlower: "flowers.sweetPeaFlower",
	species_flowers_beeBalm: "flowers.beeBalm",

	// microgreens
	species_microgreens_broccoliMicrogreen: "microgreens.broccoliMicrogreen",
	species_microgreens_radishMicrogreen: "microgreens.radishMicrogreen",
	species_microgreens_sunflowerMicrogreen: "microgreens.sunflowerMicrogreen",
	species_microgreens_peaMicrogreen: "microgreens.peaMicrogreen",
	species_microgreens_mustardMicrogreen: "microgreens.mustardMicrogreen",
	species_microgreens_arugulaMicrogreen: "microgreens.arugulaMicrogreen",
	species_microgreens_kaleMicrogreen: "microgreens.kaleMicrogreen",
	species_microgreens_cabbageMicrogreen: "microgreens.cabbageMicrogreen",
	species_microgreens_beetMicrogreen: "microgreens.beetMicrogreen",
	species_microgreens_basilMicrogreen: "microgreens.basilMicrogreen",
	species_microgreens_cilantroMicrogreen: "microgreens.cilantroMicrogreen",
	species_microgreens_amaranthMicrogreen: "microgreens.amaranthMicrogreen",
	species_microgreens_pakChoiMicrogreen: "microgreens.pakChoiMicrogreen",
	species_microgreens_turnipMicrogreen: "microgreens.turnipMicrogreen",
	species_microgreens_chiaMicrogreen: "microgreens.chiaMicrogreen",
	species_microgreens_flaxMicrogreen: "microgreens.flaxMicrogreen",
	species_microgreens_fennelMicrogreen: "microgreens.fennelMicrogreen",
	species_microgreens_dillMicrogreen: "microgreens.dillMicrogreen",
	species_microgreens_shisoMicrogreen: "microgreens.shisoMicrogreen",
	species_microgreens_watercressMicrogreen: "microgreens.watercressMicrogreen",

	// cover-crops
	species_coverCrops_whiteClover: "coverCrops.whiteClover",
	species_coverCrops_redClover: "coverCrops.redClover",
	species_coverCrops_alfalfa: "coverCrops.alfalfa",
	species_coverCrops_rye: "coverCrops.rye",
	species_coverCrops_winterWheat: "coverCrops.winterWheat",
	species_coverCrops_buckwheat: "coverCrops.buckwheat",
	species_coverCrops_hairyVetch: "coverCrops.hairyVetch",
	species_coverCrops_fieldPea: "coverCrops.fieldPea",
	species_coverCrops_oat: "coverCrops.oat",
	species_coverCrops_barley: "coverCrops.barley",
	species_coverCrops_mustardCover: "coverCrops.mustardCover",
	species_coverCrops_daikonCover: "coverCrops.daikonCover",
	species_coverCrops_sorghumSudangrass: "coverCrops.sorghumSudangrass",
	species_coverCrops_sunnHemp: "coverCrops.sunnHemp",
	species_coverCrops_phaceliaCover: "coverCrops.phaceliaCover",
	species_coverCrops_annualRyegrass: "coverCrops.annualRyegrass",
	species_coverCrops_cowpeaCover: "coverCrops.cowpeaCover",
	species_coverCrops_crimsonClover: "coverCrops.crimsonClover",
	species_coverCrops_lablab: "coverCrops.lablab",
	species_coverCrops_fabaBeanCover: "coverCrops.fabaBeanCover",
} as const);

export type ItemPresentationIconKey = (typeof ItemPresentationIconKey)[keyof typeof ItemPresentationIconKey];
