/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlantsRouteImport } from './routes/plants'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as GardeningEventsRouteImport } from './routes/gardening-events'
import { Route as CatalogRouteRouteImport } from './routes/catalog/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CatalogIndexRouteImport } from './routes/catalog/index'
import { Route as PlantPlantIdRouteImport } from './routes/plant.$plantId'
import { Route as LocationLocationIdRouteImport } from './routes/location.$locationId'
import { Route as GardeningEventGardeningEventIdRouteImport } from './routes/gardening-event.$gardeningEventId'
import { Route as CatalogSpeciesCategoriesRouteImport } from './routes/catalog/species-categories'
import { Route as CatalogSpeciesRouteImport } from './routes/catalog/species'
import { Route as CatalogCultivarsRouteImport } from './routes/catalog/cultivars'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as LocationLocationIdIndexRouteImport } from './routes/location.$locationId.index'
import { Route as LocationLocationIdLayoutRouteImport } from './routes/location.$locationId.layout'
import { Route as CatalogSpeciesDetailSpeciesIdRouteImport } from './routes/catalog/species-detail.$speciesId'
import { Route as CatalogSpeciesCategorySpeciesCategoryIdRouteImport } from './routes/catalog/species-category.$speciesCategoryId'
import { Route as CatalogCultivarCultivarIdRouteImport } from './routes/catalog/cultivar.$cultivarId'
import { Route as ApiRpcSplatRouteImport } from './routes/api/rpc.$'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const PlantsRoute = PlantsRouteImport.update({
  id: '/plants',
  path: '/plants',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const GardeningEventsRoute = GardeningEventsRouteImport.update({
  id: '/gardening-events',
  path: '/gardening-events',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRouteRoute = CatalogRouteRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CatalogRouteRoute,
} as any)
const PlantPlantIdRoute = PlantPlantIdRouteImport.update({
  id: '/plant/$plantId',
  path: '/plant/$plantId',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationLocationIdRoute = LocationLocationIdRouteImport.update({
  id: '/location/$locationId',
  path: '/location/$locationId',
  getParentRoute: () => rootRouteImport,
} as any)
const GardeningEventGardeningEventIdRoute =
  GardeningEventGardeningEventIdRouteImport.update({
    id: '/gardening-event/$gardeningEventId',
    path: '/gardening-event/$gardeningEventId',
    getParentRoute: () => rootRouteImport,
  } as any)
const CatalogSpeciesCategoriesRoute =
  CatalogSpeciesCategoriesRouteImport.update({
    id: '/species-categories',
    path: '/species-categories',
    getParentRoute: () => CatalogRouteRoute,
  } as any)
const CatalogSpeciesRoute = CatalogSpeciesRouteImport.update({
  id: '/species',
  path: '/species',
  getParentRoute: () => CatalogRouteRoute,
} as any)
const CatalogCultivarsRoute = CatalogCultivarsRouteImport.update({
  id: '/cultivars',
  path: '/cultivars',
  getParentRoute: () => CatalogRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationLocationIdIndexRoute = LocationLocationIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LocationLocationIdRoute,
} as any)
const LocationLocationIdLayoutRoute =
  LocationLocationIdLayoutRouteImport.update({
    id: '/layout',
    path: '/layout',
    getParentRoute: () => LocationLocationIdRoute,
  } as any)
const CatalogSpeciesDetailSpeciesIdRoute =
  CatalogSpeciesDetailSpeciesIdRouteImport.update({
    id: '/species-detail/$speciesId',
    path: '/species-detail/$speciesId',
    getParentRoute: () => CatalogRouteRoute,
  } as any)
const CatalogSpeciesCategorySpeciesCategoryIdRoute =
  CatalogSpeciesCategorySpeciesCategoryIdRouteImport.update({
    id: '/species-category/$speciesCategoryId',
    path: '/species-category/$speciesCategoryId',
    getParentRoute: () => CatalogRouteRoute,
  } as any)
const CatalogCultivarCultivarIdRoute =
  CatalogCultivarCultivarIdRouteImport.update({
    id: '/cultivar/$cultivarId',
    path: '/cultivar/$cultivarId',
    getParentRoute: () => CatalogRouteRoute,
  } as any)
const ApiRpcSplatRoute = ApiRpcSplatRouteImport.update({
  id: '/api/rpc/$',
  path: '/api/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteRouteWithChildren
  '/gardening-events': typeof GardeningEventsRoute
  '/locations': typeof LocationsRoute
  '/plants': typeof PlantsRoute
  '/api/$': typeof ApiSplatRoute
  '/catalog/cultivars': typeof CatalogCultivarsRoute
  '/catalog/species': typeof CatalogSpeciesRoute
  '/catalog/species-categories': typeof CatalogSpeciesCategoriesRoute
  '/gardening-event/$gardeningEventId': typeof GardeningEventGardeningEventIdRoute
  '/location/$locationId': typeof LocationLocationIdRouteWithChildren
  '/plant/$plantId': typeof PlantPlantIdRoute
  '/catalog/': typeof CatalogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/catalog/cultivar/$cultivarId': typeof CatalogCultivarCultivarIdRoute
  '/catalog/species-category/$speciesCategoryId': typeof CatalogSpeciesCategorySpeciesCategoryIdRoute
  '/catalog/species-detail/$speciesId': typeof CatalogSpeciesDetailSpeciesIdRoute
  '/location/$locationId/layout': typeof LocationLocationIdLayoutRoute
  '/location/$locationId/': typeof LocationLocationIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gardening-events': typeof GardeningEventsRoute
  '/locations': typeof LocationsRoute
  '/plants': typeof PlantsRoute
  '/api/$': typeof ApiSplatRoute
  '/catalog/cultivars': typeof CatalogCultivarsRoute
  '/catalog/species': typeof CatalogSpeciesRoute
  '/catalog/species-categories': typeof CatalogSpeciesCategoriesRoute
  '/gardening-event/$gardeningEventId': typeof GardeningEventGardeningEventIdRoute
  '/plant/$plantId': typeof PlantPlantIdRoute
  '/catalog': typeof CatalogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/catalog/cultivar/$cultivarId': typeof CatalogCultivarCultivarIdRoute
  '/catalog/species-category/$speciesCategoryId': typeof CatalogSpeciesCategorySpeciesCategoryIdRoute
  '/catalog/species-detail/$speciesId': typeof CatalogSpeciesDetailSpeciesIdRoute
  '/location/$locationId/layout': typeof LocationLocationIdLayoutRoute
  '/location/$locationId': typeof LocationLocationIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog': typeof CatalogRouteRouteWithChildren
  '/gardening-events': typeof GardeningEventsRoute
  '/locations': typeof LocationsRoute
  '/plants': typeof PlantsRoute
  '/api/$': typeof ApiSplatRoute
  '/catalog/cultivars': typeof CatalogCultivarsRoute
  '/catalog/species': typeof CatalogSpeciesRoute
  '/catalog/species-categories': typeof CatalogSpeciesCategoriesRoute
  '/gardening-event/$gardeningEventId': typeof GardeningEventGardeningEventIdRoute
  '/location/$locationId': typeof LocationLocationIdRouteWithChildren
  '/plant/$plantId': typeof PlantPlantIdRoute
  '/catalog/': typeof CatalogIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/rpc/$': typeof ApiRpcSplatRoute
  '/catalog/cultivar/$cultivarId': typeof CatalogCultivarCultivarIdRoute
  '/catalog/species-category/$speciesCategoryId': typeof CatalogSpeciesCategorySpeciesCategoryIdRoute
  '/catalog/species-detail/$speciesId': typeof CatalogSpeciesDetailSpeciesIdRoute
  '/location/$locationId/layout': typeof LocationLocationIdLayoutRoute
  '/location/$locationId/': typeof LocationLocationIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog'
    | '/gardening-events'
    | '/locations'
    | '/plants'
    | '/api/$'
    | '/catalog/cultivars'
    | '/catalog/species'
    | '/catalog/species-categories'
    | '/gardening-event/$gardeningEventId'
    | '/location/$locationId'
    | '/plant/$plantId'
    | '/catalog/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/catalog/cultivar/$cultivarId'
    | '/catalog/species-category/$speciesCategoryId'
    | '/catalog/species-detail/$speciesId'
    | '/location/$locationId/layout'
    | '/location/$locationId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gardening-events'
    | '/locations'
    | '/plants'
    | '/api/$'
    | '/catalog/cultivars'
    | '/catalog/species'
    | '/catalog/species-categories'
    | '/gardening-event/$gardeningEventId'
    | '/plant/$plantId'
    | '/catalog'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/catalog/cultivar/$cultivarId'
    | '/catalog/species-category/$speciesCategoryId'
    | '/catalog/species-detail/$speciesId'
    | '/location/$locationId/layout'
    | '/location/$locationId'
  id:
    | '__root__'
    | '/'
    | '/catalog'
    | '/gardening-events'
    | '/locations'
    | '/plants'
    | '/api/$'
    | '/catalog/cultivars'
    | '/catalog/species'
    | '/catalog/species-categories'
    | '/gardening-event/$gardeningEventId'
    | '/location/$locationId'
    | '/plant/$plantId'
    | '/catalog/'
    | '/api/auth/$'
    | '/api/rpc/$'
    | '/catalog/cultivar/$cultivarId'
    | '/catalog/species-category/$speciesCategoryId'
    | '/catalog/species-detail/$speciesId'
    | '/location/$locationId/layout'
    | '/location/$locationId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogRouteRoute: typeof CatalogRouteRouteWithChildren
  GardeningEventsRoute: typeof GardeningEventsRoute
  LocationsRoute: typeof LocationsRoute
  PlantsRoute: typeof PlantsRoute
  ApiSplatRoute: typeof ApiSplatRoute
  GardeningEventGardeningEventIdRoute: typeof GardeningEventGardeningEventIdRoute
  LocationLocationIdRoute: typeof LocationLocationIdRouteWithChildren
  PlantPlantIdRoute: typeof PlantPlantIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiRpcSplatRoute: typeof ApiRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/plants': {
      id: '/plants'
      path: '/plants'
      fullPath: '/plants'
      preLoaderRoute: typeof PlantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gardening-events': {
      id: '/gardening-events'
      path: '/gardening-events'
      fullPath: '/gardening-events'
      preLoaderRoute: typeof GardeningEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof CatalogRouteRoute
    }
    '/plant/$plantId': {
      id: '/plant/$plantId'
      path: '/plant/$plantId'
      fullPath: '/plant/$plantId'
      preLoaderRoute: typeof PlantPlantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$locationId': {
      id: '/location/$locationId'
      path: '/location/$locationId'
      fullPath: '/location/$locationId'
      preLoaderRoute: typeof LocationLocationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gardening-event/$gardeningEventId': {
      id: '/gardening-event/$gardeningEventId'
      path: '/gardening-event/$gardeningEventId'
      fullPath: '/gardening-event/$gardeningEventId'
      preLoaderRoute: typeof GardeningEventGardeningEventIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/species-categories': {
      id: '/catalog/species-categories'
      path: '/species-categories'
      fullPath: '/catalog/species-categories'
      preLoaderRoute: typeof CatalogSpeciesCategoriesRouteImport
      parentRoute: typeof CatalogRouteRoute
    }
    '/catalog/species': {
      id: '/catalog/species'
      path: '/species'
      fullPath: '/catalog/species'
      preLoaderRoute: typeof CatalogSpeciesRouteImport
      parentRoute: typeof CatalogRouteRoute
    }
    '/catalog/cultivars': {
      id: '/catalog/cultivars'
      path: '/cultivars'
      fullPath: '/catalog/cultivars'
      preLoaderRoute: typeof CatalogCultivarsRouteImport
      parentRoute: typeof CatalogRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/location/$locationId/': {
      id: '/location/$locationId/'
      path: '/'
      fullPath: '/location/$locationId/'
      preLoaderRoute: typeof LocationLocationIdIndexRouteImport
      parentRoute: typeof LocationLocationIdRoute
    }
    '/location/$locationId/layout': {
      id: '/location/$locationId/layout'
      path: '/layout'
      fullPath: '/location/$locationId/layout'
      preLoaderRoute: typeof LocationLocationIdLayoutRouteImport
      parentRoute: typeof LocationLocationIdRoute
    }
    '/catalog/species-detail/$speciesId': {
      id: '/catalog/species-detail/$speciesId'
      path: '/species-detail/$speciesId'
      fullPath: '/catalog/species-detail/$speciesId'
      preLoaderRoute: typeof CatalogSpeciesDetailSpeciesIdRouteImport
      parentRoute: typeof CatalogRouteRoute
    }
    '/catalog/species-category/$speciesCategoryId': {
      id: '/catalog/species-category/$speciesCategoryId'
      path: '/species-category/$speciesCategoryId'
      fullPath: '/catalog/species-category/$speciesCategoryId'
      preLoaderRoute: typeof CatalogSpeciesCategorySpeciesCategoryIdRouteImport
      parentRoute: typeof CatalogRouteRoute
    }
    '/catalog/cultivar/$cultivarId': {
      id: '/catalog/cultivar/$cultivarId'
      path: '/cultivar/$cultivarId'
      fullPath: '/catalog/cultivar/$cultivarId'
      preLoaderRoute: typeof CatalogCultivarCultivarIdRouteImport
      parentRoute: typeof CatalogRouteRoute
    }
    '/api/rpc/$': {
      id: '/api/rpc/$'
      path: '/api/rpc/$'
      fullPath: '/api/rpc/$'
      preLoaderRoute: typeof ApiRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CatalogRouteRouteChildren {
  CatalogCultivarsRoute: typeof CatalogCultivarsRoute
  CatalogSpeciesRoute: typeof CatalogSpeciesRoute
  CatalogSpeciesCategoriesRoute: typeof CatalogSpeciesCategoriesRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  CatalogCultivarCultivarIdRoute: typeof CatalogCultivarCultivarIdRoute
  CatalogSpeciesCategorySpeciesCategoryIdRoute: typeof CatalogSpeciesCategorySpeciesCategoryIdRoute
  CatalogSpeciesDetailSpeciesIdRoute: typeof CatalogSpeciesDetailSpeciesIdRoute
}

const CatalogRouteRouteChildren: CatalogRouteRouteChildren = {
  CatalogCultivarsRoute: CatalogCultivarsRoute,
  CatalogSpeciesRoute: CatalogSpeciesRoute,
  CatalogSpeciesCategoriesRoute: CatalogSpeciesCategoriesRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  CatalogCultivarCultivarIdRoute: CatalogCultivarCultivarIdRoute,
  CatalogSpeciesCategorySpeciesCategoryIdRoute:
    CatalogSpeciesCategorySpeciesCategoryIdRoute,
  CatalogSpeciesDetailSpeciesIdRoute: CatalogSpeciesDetailSpeciesIdRoute,
}

const CatalogRouteRouteWithChildren = CatalogRouteRoute._addFileChildren(
  CatalogRouteRouteChildren,
)

interface LocationLocationIdRouteChildren {
  LocationLocationIdLayoutRoute: typeof LocationLocationIdLayoutRoute
  LocationLocationIdIndexRoute: typeof LocationLocationIdIndexRoute
}

const LocationLocationIdRouteChildren: LocationLocationIdRouteChildren = {
  LocationLocationIdLayoutRoute: LocationLocationIdLayoutRoute,
  LocationLocationIdIndexRoute: LocationLocationIdIndexRoute,
}

const LocationLocationIdRouteWithChildren =
  LocationLocationIdRoute._addFileChildren(LocationLocationIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogRouteRoute: CatalogRouteRouteWithChildren,
  GardeningEventsRoute: GardeningEventsRoute,
  LocationsRoute: LocationsRoute,
  PlantsRoute: PlantsRoute,
  ApiSplatRoute: ApiSplatRoute,
  GardeningEventGardeningEventIdRoute: GardeningEventGardeningEventIdRoute,
  LocationLocationIdRoute: LocationLocationIdRouteWithChildren,
  PlantPlantIdRoute: PlantPlantIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiRpcSplatRoute: ApiRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
