import { createElement } from "react";
import {
	IconAppleFilled,
	IconBasket,
	IconCarrot,
	IconCarrotOff,
	IconCherry,
	IconDropletsFilled,
	IconFlower,
	IconFlowerFilled,
	IconGrain,
	IconLeaf,
	IconLeaf2,
	IconLeafFilled,
	IconLeafOff,
	IconShovel,
	IconGrowth,
	IconWorldLongitude,
	IconFileTextFilled,
	type IconProps,
} from "@tabler/icons-react";
import {
	ItemPresentationIconKey as ItemPresentationIconKeyValues,
	type ItemPresentationIconKey,
} from "@backend/core/domain/gardening/enums";

export const ITEM_PRESENTATION_ICON_NODE_MAP: Record<ItemPresentationIconKey, React.ComponentType<IconProps>> = {
	// actions
	[ItemPresentationIconKeyValues.action_watering]: IconDropletsFilled,
	[ItemPresentationIconKeyValues.action_fertilization]: IconFlower,
	[ItemPresentationIconKeyValues.action_pruning]: IconLeafOff,
	[ItemPresentationIconKeyValues.action_harvesting]: IconBasket,
	[ItemPresentationIconKeyValues.action_transplanting]: IconShovel,
	[ItemPresentationIconKeyValues.action_note]: IconFileTextFilled,

	// generic
	[ItemPresentationIconKeyValues.generic_carrot]: IconCarrot,
	[ItemPresentationIconKeyValues.generic_leaf]: IconLeaf,
	[ItemPresentationIconKeyValues.generic_apple]: IconAppleFilled,
	[ItemPresentationIconKeyValues.generic_cherry]: IconCherry,
	[ItemPresentationIconKeyValues.generic_leaf2]: IconLeaf2,
	[ItemPresentationIconKeyValues.generic_basket]: IconBasket,
	[ItemPresentationIconKeyValues.generic_flower]: IconFlower,
	[ItemPresentationIconKeyValues.generic_grain]: IconGrain,
	[ItemPresentationIconKeyValues.generic_carrot_off]: IconCarrotOff,
	[ItemPresentationIconKeyValues.generic_flower_filled]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.generic_leaf_filled]: IconLeafFilled,

	// categories
	[ItemPresentationIconKeyValues.category_vegetables]: IconCarrot,
	[ItemPresentationIconKeyValues.category_herbs]: IconLeaf,
	[ItemPresentationIconKeyValues.category_fruits]: IconAppleFilled,
	[ItemPresentationIconKeyValues.category_berries]: IconCherry,
	[ItemPresentationIconKeyValues.category_leafyGreens]: IconLeaf2,
	[ItemPresentationIconKeyValues.category_alliums]: IconWorldLongitude,
	[ItemPresentationIconKeyValues.category_brassicas]: IconFlower,
	[ItemPresentationIconKeyValues.category_legumes]: IconGrain,
	[ItemPresentationIconKeyValues.category_rootCrops]: IconCarrotOff,
	[ItemPresentationIconKeyValues.category_flowers]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.category_microgreens]: IconLeafFilled,
	[ItemPresentationIconKeyValues.category_coverCrops]: IconGrowth,

	// species
	[ItemPresentationIconKeyValues.species_vegetables_tomato]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_cucumber]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_zucchini]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_eggplant]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_bellPepper]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_chiliPepper]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_pumpkin]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_squash]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_corn]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_okra]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_artichoke]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_celery]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_asparagus]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_rhubarb]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_sweetPotato]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_tomatillo]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_pattypanSquash]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_chayote]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_kohlrabi]: IconCarrot,
	[ItemPresentationIconKeyValues.species_vegetables_fennel]: IconCarrot,
	[ItemPresentationIconKeyValues.species_herbs_basil]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_parsley]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_cilantro]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_dill]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_mint]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_oregano]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_thyme]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_rosemary]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_sage]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_chives]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_tarragon]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_marjoram]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_lavender]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_lemonBalm]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_bayLaurel]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_lemongrass]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_stevia]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_chervil]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_summerSavory]: IconLeaf,
	[ItemPresentationIconKeyValues.species_herbs_winterSavory]: IconLeaf,
	[ItemPresentationIconKeyValues.species_fruits_apple]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_pear]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_peach]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_plum]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_apricot]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_cherry]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_fig]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_persimmon]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_quince]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_grape]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_kiwi]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_melon]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_watermelon]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_pineapple]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_pomegranate]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_orange]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_lemon]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_lime]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_mango]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_fruits_papaya]: IconAppleFilled,
	[ItemPresentationIconKeyValues.species_berries_strawberry]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_blueberry]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_raspberry]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_blackberry]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_gooseberry]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_redCurrant]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_blackCurrant]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_whiteCurrant]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_cranberry]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_lingonberry]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_elderberry]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_mulberry]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_boysenberry]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_loganberry]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_huckleberry]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_serviceberry]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_seaBuckthorn]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_aronia]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_cloudberry]: IconCherry,
	[ItemPresentationIconKeyValues.species_berries_jostaberry]: IconCherry,
	[ItemPresentationIconKeyValues.species_leafyGreens_lettuce]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_spinach]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_kale]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_arugula]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_swissChard]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_collardGreens]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_endive]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_escarole]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_mustardGreens]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_bokChoy]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_romaine]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_radicchio]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_watercress]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_mizuna]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_tatsoi]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_newZealandSpinach]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_purslane]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_sorrel]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_malabarSpinach]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_leafyGreens_chicory]: IconLeaf2,
	[ItemPresentationIconKeyValues.species_alliums_onion]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_garlic]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_leek]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_shallot]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_scallion]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_garlicChive]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_onionChive]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_welshOnion]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_walkingOnion]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_rakkyo]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_elephantGarlic]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_ramps]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_garlicChives]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_springOnion]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_redOnion]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_yellowOnion]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_whiteOnion]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_pearlOnion]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_cipolliniOnion]: IconBasket,
	[ItemPresentationIconKeyValues.species_alliums_societyGarlic]: IconBasket,
	[ItemPresentationIconKeyValues.species_brassicas_cabbage]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_broccoli]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_cauliflower]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_brusselsSprouts]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_broccolini]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_napaCabbage]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_savoyCabbage]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_redCabbage]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_romanesco]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_turnip]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_rutabaga]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_daikon]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_wasabi]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_horseradish]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_komatsuna]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_broccoliRaab]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_mustardCabbage]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_chineseBroccoli]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_pakChoi]: IconFlower,
	[ItemPresentationIconKeyValues.species_brassicas_canola]: IconFlower,
	[ItemPresentationIconKeyValues.species_legumes_pea]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_snapPea]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_snowPea]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_greenBean]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_runnerBean]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_limaBean]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_favaBean]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_chickpea]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_lentil]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_soybean]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_peanut]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_cowpea]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_pigeonPea]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_blackEyedPea]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_adzukiBean]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_mungBean]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_kidneyBean]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_navyBean]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_pintoBean]: IconGrain,
	[ItemPresentationIconKeyValues.species_legumes_borlottiBean]: IconGrain,
	[ItemPresentationIconKeyValues.species_rootCrops_carrot]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_beet]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_radish]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_parsnip]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_turnipRoot]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_celeriac]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_salsify]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_scorzonera]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_yacon]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_jicama]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_burdock]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_skirret]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_cassava]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_taro]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_yam]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_ginger]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_turmeric]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_horseradishRoot]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_daikonRoot]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_rootCrops_rutabagaRoot]: IconCarrotOff,
	[ItemPresentationIconKeyValues.species_flowers_marigold]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_nasturtium]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_calendula]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_borage]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_chamomile]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_sunflower]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_zinnia]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_cosmos]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_lavenderFlower]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_echinacea]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_yarrow]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_alyssum]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_phacelia]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_cornflower]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_dahlia]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_pansy]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_viola]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_snapdragon]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_sweetPeaFlower]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_flowers_beeBalm]: IconFlowerFilled,
	[ItemPresentationIconKeyValues.species_microgreens_broccoliMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_radishMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_sunflowerMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_peaMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_mustardMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_arugulaMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_kaleMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_cabbageMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_beetMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_basilMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_cilantroMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_amaranthMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_pakChoiMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_turnipMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_chiaMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_flaxMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_fennelMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_dillMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_shisoMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_microgreens_watercressMicrogreen]: IconLeafFilled,
	[ItemPresentationIconKeyValues.species_coverCrops_whiteClover]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_redClover]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_alfalfa]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_rye]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_winterWheat]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_buckwheat]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_hairyVetch]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_fieldPea]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_oat]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_barley]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_mustardCover]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_daikonCover]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_sorghumSudangrass]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_sunnHemp]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_phaceliaCover]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_annualRyegrass]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_cowpeaCover]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_crimsonClover]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_lablab]: IconGrain,
	[ItemPresentationIconKeyValues.species_coverCrops_fabaBeanCover]: IconGrain,
};

export const ITEM_PRESENTATION_ICON_KEYS = Object.keys(ITEM_PRESENTATION_ICON_NODE_MAP) as ItemPresentationIconKey[];

export function resolveItemPresentationIconNode(iconKey: string, props?: IconProps): React.ReactNode | undefined {
	const IconComponent = ITEM_PRESENTATION_ICON_NODE_MAP[iconKey as ItemPresentationIconKey];
	if (!IconComponent) return undefined;
	return createElement(IconComponent, props);
}
